language: node_js
node_js:
  - "10"
install:
  - npm install
stages:
  - "Quality gates"
jobs:
  include:
    - stage: "Quality gates Linter"
      name: "Linter"
      script: npm run lint
    - script: npm run test-headless
      name: "Unit Tests"
branches:
  only:
  - master
before_deploy:
  - npm run deploy-gh
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: GITHUB_TOKEN
  local_dir: dist/bitbucket
  on:
    branch: master
